name: tictac_duel
description: "Real-time multiplayer Tic-Tac-Toe"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  socket_io_client: ^3.1.6
  provider: ^6.1.5+1
  go_router: ^18.0.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  icons_launcher: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/app/

icons_launcher:
  platforms:
    android:
      enable: true
      image_path: "assets/app/icon_foreground.png"
      adaptive_background_image: "assets/app/icon_background.png"
      adaptive_foreground_image: "assets/app/icon_foreground.png"

    ios:
      enable: true
      image_path: "assets/app/icon_foreground.png"